AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: go1.x
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 10
      MemorySize: 2048
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiDeployment

Outputs:
  SampleGqlGenApi:
    Description: URL for application
    Value: !Sub "https://${ApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
    Export:
      Name: SampleGqlGenApi
